backend:
  name: github
  repo: agenciaglobal/web

media_folder: content/assets
public_folder: assets

collections:
  - name: news
    label: Not√≠cias
    folder: content/news
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
  - name: client
    label: Clientes
    folder: content/client
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: name, label: Name }
      - { name: description, label: Description }
  - name: portifolio
    label: Portifolio
    folder: content/portifolio
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - label: "Image"
        name: "image"
        widget: "image"
        default: "/uploads/chocolate-dogecoin.jpg"
        media_library:
          config:
            multiple: true
      - name: categorie
        label: Categorie
        widget: select
        options:
          - { label: "featured", value: "featured" }
          - { label: "digital", value: "digital" }
          - { label: "social", value: "social" }
          - { label: "crm", value: "crm" }
          - { label: "advertising", value: "advertising" }
  - name: team
    label: Team
    folder: content/team
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: name, label: Title }
      - { name: job, label: Description }
      - label: "Image"
        name: "image"
        widget: "image"
        default: "/uploads/chocolate-dogecoin.jpg"
        media_library:
          config:
            multiple: true
